本周只有一个代码实践题

以下代码课用来加载 预先训练好的模型,你需要只需要修改模型的存放路径即可（第二行代码）

In [1]:
#!pip install transformers

In [1]:
import torch
import torch.nn.functional as F
from transformers import GPT2Tokenizer, GPT2LMHeadModel, GPT2Config
from torch.utils.data import DataLoader,Dataset
from torch.nn.utils.rnn import pad_sequence

第一步 使用以下链接下载相应预训练模型

https://convaisharables.blob.core.windows.net/lsp/multiref/small_ft.pkl

In [2]:
tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
weights = torch.load('F:/nlp/small_ft.pkl')  #
medium_config = GPT2Config(n_embd = 768,n_layer = 12, n_head = 12)
model = GPT2LMHeadModel(medium_config)

weights['lm_head.weight'] = weights['lm_head.decoder.weight']
weights.pop('lm_head.decoder.weight',None)

model.load_state_dict(weights)
model.train()

GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50257, 768)
    (wpe): Embedding(1024, 768)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0): Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): Attention(
          (c_attn): Conv1D()
          (c_proj): Conv1D()
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (mlp): MLP(
          (c_fc): Conv1D()
          (c_proj): Conv1D()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
      (1): Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): Attention(
          (c_attn): Conv1D()
          (c_proj): Conv1D()
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): Laye

In [5]:
type(weights)

dict

In [69]:
tokenizer.encode('I like playing basketball.<|endoftext|>I do not like playing')

[40, 588, 2712, 9669, 13, 50256, 40, 466, 407, 588, 2712]

In [14]:
tokenizer.decode([40, 588, 2712, 9669, 13])

'I like playing basketball.'

In [1]:
from random import randint

In [8]:
randint(0,6)

5

你需要写一个推理函数，这个函数接收一个英文句子为输入，输出一个回应。

In [3]:
def token_predict(sentence):
    output=[]
    #input_ids = sum([tokenizer.encode(sentence)],[])
    input_ids = tokenizer.encode(sentence)
    
    #print(torch.tensor(input_ids,dtype=torch.long))
    input_ids = pad_sequence([torch.tensor(input_ids,dtype=torch.long)],batch_first=True,padding_value=0)   #https://pytorch.org/docs/stable/nn.html?highlight=torch%20nn%20utils%20rnn#torch.nn.utils.rnn.pack_sequence
    
    #print(input_ids)
    
    prediction_scores,past= model(input_ids=input_ids)       #https://huggingface.co/transformers/model_doc/gpt2.html?highlight=gpt2lmheadmodel#gpt2lmheadmodel
    
    #print(prediction_scores.size())
    lm_logits= prediction_scores[0][-1]   #最后一个词的score
    #print(lm_logits)
    softmax = F.softmax(lm_logits, dim=-1)   
    softmax, indices = torch.sort(softmax, descending = True)    #https://pytorch.org/docs/stable/torch.html?highlight=torch%20sort#torch.sort
    #print(softmax)
    #print(type(tokenizer.decode([indices[0]])))
    
    return tokenizer.decode([indices[0]])  #排序之后indices[0]位置id的词概率最大
   
    
    
    
def predict(sentence):
    end_text = '<|endoftext|>'
    while 1:
        next_token = token_predict(sentence)
        if next_token == end_text:
            return sentence + end_text
        else:
            sentence += next_token    
    

In [5]:
token_predict('Does money buy happiness ?<|endoftext|>')

'Money'

### 测试语句 
一轮对话   
1. Does money buy happiness ?   
2. What is the best way to buy happiness?   

一轮对话   
1. what is the meaning of a godd life ?   
2. How to be a good person ?   

In [38]:
import numpy as np

In [54]:
x = torch.randn(3, 4)
x

tensor([[-0.5516, -0.5128,  1.7565,  0.5665],
        [ 1.2391, -0.9357,  0.3812,  0.9905],
        [ 0.2809,  0.2110,  0.4272, -0.5525]])

In [55]:
sorted, indices = torch.sort(x)

In [56]:
sorted

tensor([[-0.5516, -0.5128,  0.5665,  1.7565],
        [-0.9357,  0.3812,  0.9905,  1.2391],
        [-0.5525,  0.2110,  0.2809,  0.4272]])

In [58]:
indices

tensor([[0, 1, 3, 2],
        [1, 2, 3, 0],
        [3, 1, 0, 2]])

In [94]:
a = torch.ones(25, 300)
b = torch.ones(22, 300)                                                                                                                                                                                                                                                l
c = torch.ones(15, 300                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       

In [98]:
pad_sequence([a, b, c]).size()

torch.Size([25, 3, 300])

In [81]:
sum([tokenizer.encode('I like playing basketball.')],[])

[40, 588, 2712, 9669, 13]

In [112]:
a=torch.tensor([   40,   588,  2712,  9669,    13, 50256,    40,   466,   407,   588,
          2712])
a.size()

torch.Size([11])

In [9]:
predict('I like playing basketball.<|endoftext|>I do not like playing ')

'I like playing basketball.<|endoftext|>I do not like playing  basketball<|endoftext|>'

In [6]:
predict('Does money buy happiness ?<|endoftext|>')

'Does money buy happiness ?<|endoftext|>I love that money.Money<|endoftext|>'

In [7]:
predict('what is the meaning of a godd life ?<|endoftext|>')

'what is the meaning of a godd life ?<|endoftext|>What is the meaning of intercourse.com?<|endoftext|>'

In [8]:
predict('How to be a good person ?<|endoftext|>')

'How to be a good person ?<|endoftext|>What is challengin<|endoftext|>'