# Assignment 12

参考作业见https://nbviewer.jupyter.org/github/kkb-Alex/kaikeba/blob/master/Assignment-12/Assignment_12.ipynb

### 1.复习上课内容

### 2.回答以下理论问题

#### 1. 请写一下TF-IDF的计算公式

TF是词频(Term Frequency):在一个文档中，一个词出现的次数: 
$$tf_{td}=count(t,d)$$

$$tf_{td}=log_{10}\big(count(t,d)+1\big)$$

其中，t=某个词在该文档中出现对频次，d=文档的总词数

IDF是逆向文件频率(Inverse Document Frequency):总文档数除以包含某个词的文档数，再取对数: 
$$idf_t=log_{10}\big( \frac{N}{df_t}\big)$$
其中，N=总文档数，$df_t$=包含t的文档数

TF-IDF实际上是：$$W_{t,d}=tf_{td}*idf_t$$

#### 2. LDA算法的基本假设是什么？


LDA的2个基本假设：

1.Per-document topic distributions: The topics of each document obey a probability distribution(每个文本主题服从某个概率分布)

2.Per-topic word distributions: The words of each topic obey a probability distribution (每个主题下的词服从一个概率分布)

#### 3. 在TextRank算法中构建图的权重是如何得到的？

A：$$WS(V_i)=(1-d)+d*\sum_{V_j\in In(V_i)}\frac {w_{ji}}{\sum_{V_k\in Out(V_j)}w_{jk}}WS(V_j)$$


一般是通过计算2个词的词向量之间的余弦相似度来得到的:$$w_{ji}=similarity  cosine(w_i,w_j)$$

#### 4. 什么是命名实体识别？ 有什么应用场景？

A: 命名实体识别 指从文本中识别出命名性指称项，为关系抽取等任务做铺垫。

            
Named entity recognitions(NER): To find each menthon of a named entity in the text and label its type (识别文档中的实体(比如地点，人名，时间等)并加上标签)

NER types are appliction specific:

通常包括人、地点和组织

生物医学领域:基因和蛋白质的名字

教育：大学课程的代码


#### 5.NLP主要有哪几类任务 ？

A: 1、分类任务：文本分类、sentiment classification。sequence2sequence, sequence-2-1
   
   2、生成任务:machine translation、 question answering、 text summarization
     
   
 
分类任务(Classification tasks):
情感分析，
文本分类，
实体识别。

生成任务(Generation tasks)：
机器翻译，
对话系统(QA)，
文本生成。
   

### 3.实践题

#### 3.1 手动实现TextRank算法 (在新闻数据中随机提取100条新闻训练词向量和做做法测试）

 提示：
 1. 确定窗口，建立图链接。   
 2. 通过词向量相似度确定图上边的权重
 3. 根据公式实现算法迭代(d=0.85)

训练词向量

In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
import random
import re
import jieba

In [2]:
#m = sum(1 for line in new_f["content"]) - 1 #number of records in file (excludes header)
#s = 99 #desired sample size
#skip = sorted(random.sample(range(1,m+1),m-s)) #the 0-indexed header will not be included in the skip list
#df1 = pd.read_csv('F:/export_sql_1558435/sqlResult_1558435new5.csv', skiprows=skip)

In [3]:
news = pd.read_csv('F:/export_sql_1558435/sqlResult_1558435.csv',encoding='ANSI')

In [4]:
news = news.fillna('')

In [5]:
news.columns.values

array(['id', 'author', 'source', 'content', 'feature', 'title', 'url'],
      dtype=object)

In [6]:
content = news['content'].tolist()

In [7]:
content[0] 

'此外，自本周（6月12日）起，除小米手机6等15款机型外，其余机型已暂停更新发布（含开发版/体验版内测，稳定版暂不受影响），以确保工程师可以集中全部精力进行系统优化工作。有人猜测这也是将精力主要用到MIUI 9的研发之中。\r\nMIUI 8去年5月发布，距今已有一年有余，也是时候更新换代了。\r\n当然，关于MIUI 9的确切信息，我们还是等待官方消息。\r\n'

In [8]:
# 读取中文停用词
    
stopword_set = set()
with open("F:/BaiduYunDownload/Project01/content/stopwords.txt", 'r', encoding="utf-8") as stopwords:    # stopwords.txt停用词表，我放在同一目录下
    for stopword in stopwords:
        stopword_set.add(stopword.strip("\n"))
    stopword_set = [i.strip() for i in stopword_set] 

In [9]:
def cut(string):
    return ' '.join(token for token in jieba.cut(''.join(re.sub('\\\\n|[\n\u3000\r]', '', string))) 
                    if token not in stopword_set)

In [10]:
# test
cut(content[0])

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\lenovo\AppData\Local\Temp\jieba.cache
Loading model cost 1.750 seconds.
Prefix dict has been built succesfully.


'本周 6 月 12 日 小米 手机 6 15 款 机型 外 机型 已 暂停 更新 发布 含 开发 版 体验版 内测 稳定版 暂不受 影响 确保 工程师 集中 全部 精力 进行 系统优化 工作 有人 猜测 精力 主要 用到 MIUI   9 研发 之中 MIUI   8 去年 5 月 发布 距今已有 一年 有余 更新换代 当然 MIUI   9 确切 信息 等待 官方消息'

In [11]:
sample_content = random.sample(content, 100)

In [12]:
new_content = [cut(c) for c in sample_content]

In [13]:
new_content[1]

'新华社 照片 外代 2017 年 5 月 28 日 外代 二线 虞美人 这是 5 月 26 日 匈牙利 首都 布达佩斯 东北 110 公里 处 索沙 哈特 雅 拍摄 虞美人 花 新华社 欧新'

In [14]:
vectorizer = TfidfVectorizer(token_pattern='(?u)\\b\\w+\\b') # 默认pattern是只匹配长度至少为2的词

In [15]:
X = vectorizer.fit_transform(new_content)

In [16]:
X.shape

(100, 5391)

In [90]:
X[:5].toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.05093009, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [94]:
#X.toarray()
X[:,vectorizer.vocabulary_['省']].toarray()

array([[0.16872734],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.04123243],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.04558525],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.   

In [105]:
#sorted(vectorizer.vocabulary_.values(),reverse=True)
vectorizer.vocabulary_

{'新华社': 2909,
 '照片': 3624,
 '外代': 1787,
 '2017': 56,
 '年': 2275,
 '5': 102,
 '月': 3090,
 '6': 116,
 '日': 2965,
 '二线': 586,
 '印尼': 1333,
 '举办': 524,
 '泗水': 3436,
 '时装展': 2999,
 '印度尼西亚': 1335,
 '东': 413,
 '爪哇': 3632,
 '省': 3855,
 '首府': 5284,
 '一名': 204,
 '模特': 3272,
 '上': 304,
 '展示': 2159,
 '时装': 2997,
 '法新': 3427,
 '28': 74,
 '虞美人': 4478,
 '这是': 4896,
 '26': 71,
 '匈牙利': 1240,
 '首都': 5292,
 '布达佩斯': 2237,
 '东北': 415,
 '110': 13,
 '公里': 953,
 '处': 1769,
 '索沙': 4118,
 '哈特': 1564,
 '雅': 5169,
 '拍摄': 2681,
 '花': 4398,
 '欧新': 3286,
 '中国': 462,
 '证券网': 4617,
 '讯': 4588,
 '记者': 4591,
 '费': 4704,
 '天元': 1870,
 '周四': 1548,
 '午后': 1269,
 '市场': 2222,
 '抛压': 2637,
 '剧增': 1173,
 '三大': 295,
 '指数': 2713,
 '放量': 2839,
 '跳水': 4777,
 '沪': 3400,
 '指日线': 2714,
 '收出': 2813,
 '长': 5087,
 '上影': 322,
 '创业板': 1119,
 '指': 2706,
 '遭遇': 4970,
 '重挫': 5023,
 '截至': 2552,
 '收盘': 2818,
 '上证指数': 334,
 '报': 2647,
 '3147': 83,
 '45': 99,
 '点': 3604,
 '下跌': 350,
 '0': 0,
 '成交': 2519,
 '2204': 63,
 '亿元': 659,
 '深证': 3527,
 '成

In [96]:
#print(X[:1])

In [97]:
def get_wv(word):
    #print(X[:, vectorizer.vocabulary_[word]].toarray())
    return X[:,vectorizer.vocabulary_[word]].toarray()

In [98]:
wordvec_dict = {}
for word in vectorizer.vocabulary_.keys():
    wordvec_dict[word] = get_wv(word)
    #print(word)
    #print(wordvec_dict[word])

In [77]:
wordvec_dict

{'新华社': array([[0.09546154],
        [0.11133607],
        [0.        ],
        [0.06819109],
        [0.01425296],
        [0.08848149],
        [0.07915032],
        [0.07714086],
        [0.        ],
        [0.09142915],
        [0.        ],
        [0.08101567],
        [0.0097111 ],
        [0.08635159],
        [0.03987908],
        [0.08129876],
        [0.04408683],
        [0.03378733],
        [0.00853392],
        [0.10027596],
        [0.06281754],
        [0.08379629],
        [0.0070929 ],
        [0.04124266],
        [0.05953541],
        [0.08986332],
        [0.04724588],
        [0.03111438],
        [0.05421261],
        [0.07240194],
        [0.08706226],
        [0.07459438],
        [0.00233282],
        [0.04165863],
        [0.06905495],
        [0.06280619],
        [0.01289547],
        [0.07695393],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.07837822],
        [0.08060901],
        [0.06128665],
        [0.        ],
   

TextRank算法实现
$$WS(V_i)=(1-d)+d*\sum_{V_j\in In(V_i)}\frac {w_{ji}}{\sum_{V_k\in Out(V_j)}w_{jk}}WS(V_j)$$

In [20]:
from collections import defaultdict

In [21]:
class TextRank():
    
    def __init__(self, content, wv):
        self.content = content
        self.wv = wv
        self.wordmap = defaultdict(set)
        
    # 添加关系
    def add_to_wordmap(self, words):
        for i in range(len(words) - 1):
            for j in range(len(words[i:]) - 1):
                # 因为要用词向量计算权重，因此如果某个词没有词向量，则不建立联系
                if words[i] != words[j] and words[i] in self.wv and words[j] in self.wv:
                    self.wordmap[words[i]].add(words[j])
                    self.wordmap[words[j]].add(words[i])
    
    # 根据窗口大小构建关系图
    def createNodes(self, window=3):
        word_list = self.content.split()
        if len(word_list) < window:
            self.add_to_wordmap(word_list)
        else:
            for i in range(len(word_list) - window + 1):
                self.add_to_wordmap(word_list[i:i+window])
    
    def cosine(self, word1, word2):
        wv1 = self.wv[word1]
        wv2 = self.wv[word2]
        return np.dot(wv1.T, wv2)[0][0] / (np.linalg.norm(wv1) * np.linalg.norm(wv2))
    
    # 根据关系构建矩阵
    def createMatrix(self):
        self.words = list(self.wordmap.keys())
        self.matrix = np.zeros([len(self.words), len(self.words)])
        self.word_index = {}
        
        for i, word in enumerate(self.words):
            self.word_index[word] = i
        
        for word_i in self.words:
            for word_j in self.wordmap[word_i]:
                weight = self.cosine(word_i, word_j) / sum([self.cosine(word_j, word_k) for word_k in self.wordmap[word_j]])
                self.matrix[self.word_index[word_i], self.word_index[word_j]] = weight
    
    def calculate(self, num_iters = 1000, d=0.85):
        self.WS = np.ones([len(self.words), 1]) / len(self.words)
        for i in range(num_iters):
            self.WS = (1 - d) + d * np.dot(self.matrix, self.WS)
    
    def get_result(self):
        ws_dict = {}
        for word in self.words:
            ws_dict[word] = self.WS[self.word_index[word]][0]
        return ws_dict

In [56]:
a=np.zeros([2,4])
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [58]:
a[1,3]=8
a

array([[0., 0., 0., 8.],
       [0., 0., 0., 8.]])

In [59]:
 np.ones([5,1])

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [131]:
# test
def test_textrank(content, topn=10):
    tk = TextRank(content, wordvec_dict)
    tk.createNodes(window=3)
    tk.createMatrix()
    tk.calculate(num_iters=1000, d=0.85)
    ws = tk.get_result()
    for item in sorted(ws.items(), key=lambda x: x[1], reverse=True)[:10]:
        print('word:{0:{2}<5}, weight:{1:.4f}'.format(item[0], item[1], chr(12288)))

In [132]:
choice=random.choice(new_content)
print(choice)
test_textrank(choice)

原 标题 爸爸 我错 … … 救 轻生 女儿 父亲 跳入 小清河 却 再也 没 上来 … 今天 父亲节 却是 最 悲伤 一天 父亲 没 等到 没有 听到 那句 爸爸 节日快乐 16 日晚 7 点 左右 历城区 华山 路段 小清河 观光 桥 附近 年轻 女子 疑因 感情 问题 跳入 小清河 岸边 水性 不好 父亲 未作 丝毫 犹豫 随之 跳入 河 中 抓住 女儿 后 拼尽 全身 力气 女儿 往上 托举 过路 小伙 听见 求救 后 跳入 水中 围观 市民 帮助 下 女孩 救 上岸 昏暗 路灯 下 河面 恢复 往常 平静 父亲 身影 却 已 不见 爸爸 我错 … … 女孩 坐在 岸边 浑身 颤抖地 哭喊 事发 水域   记者 丁国彬   摄 事发 突然   女孩 赌气 跳进 小清河 父亲 紧抱 女儿 用力 托举 17 日 上午 11 点 华山路 附近 小清河 河水 西向东 平缓 流淌 横跨 河面 一座 观光 桥 西侧 一米 多高 护栏 上 一处 缺口 下方 不足 半米 高 木桩 尚 不到 膝盖 位置 16 日晚 该处 位置 一男一女 相继 落河 时间 回到 当晚 7 点 居民 饭后 小清河 南北 两岸 散步 家住 附近 张女士 小清河 北岸 走 一处 木桩 时 看到 50 岁 左右 男子 年轻 女子 争吵 不 要你管 不行 … … 本想 上前 劝架 张女士 还 未 走 跟前 年轻 女子 突然 跳入 小清河 木桩 上方 护栏 缺口处 跳下去 旁边 男子 没有 丝毫 犹豫 紧跟着 跳 下去 男子 跳入 水中 后 奋力 女子 游 去 两人 河水 向西 冲出 四五米 远后 男子 才 抓住 落水 女子 大声 呼喊 救命 双手 紧紧 抱住 女子 用力 向上 托举 水性 不好 多次 呛水 张女士 说 当时 已经 吓傻 几秒钟 后 才 反应 过来 赶紧 站 岸边 过往 过路 居民 呼救 有人 落水 快 救人 河 对岸 散步 刘先生 刚好 目睹 一幕 发生 赶忙 拨打 求救 电话 多人 相救   小伙 纵身 跳河 救人 七旬 老人 绳索 拉 人 一名 30 岁 左右 过路 小伙 听到 呼救声 跑 河边 扶 岸边 栏杆 确定 两人 落水 位置 后 蹲 岸边 双手 扒 木桩 脚蹬 河岸 水泥墙 背身 跃入 河 观察 下 蹲 入河 一点 都 没 犹豫 衣服 都 没 来得及 脱 张女士 说 河 中

### 3.2 使用词向量和k-means的方法寻找关键词

提示：   
1.使用3.1训练好的词向量   
2.可使用sklearn等机器学习库

In [24]:
from sklearn.cluster import KMeans

In [25]:
class keyword_kmeans():
    
    def __init__(self, train_wv, wv_dict, n_clusters=3, max_iter=500):
        self.centers = KMeans(n_clusters=n_clusters, max_iter=max_iter).fit(train_wv).cluster_centers_
        self.wv_dict = wv_dict
        
    def distance(self, wordvec):
        dist_l = []
        for i, center in enumerate(self.centers):
            dist = np.dot(center, wordvec)[0] / (np.linalg.norm(center) * np.linalg.norm(wordvec))
            dist_l.append((i, dist))
        return max(dist_l, key=lambda x: x[1])
    
    def calculate(self, content, topn=10):
        words = list(set(content.split()))
        self.keywords = sorted([(word, self.distance(self.wv_dict[word])) for word in words if word in self.wv_dict], 
                               key=lambda x:x[1][1], reverse=True)[:topn]
    
    def get_result(self, print_out=True):
        if print_out:
            for word, (center, dist) in self.keywords:
                print('word:{0:{3}<4}, center:{1:<2}, distance:{2:.4f}'.format(word, center, dist, chr(12288)))
        else:
            return self.keywords

In [26]:
kk = keyword_kmeans(X.T, wordvec_dict, n_clusters=3)

In [27]:
kk.calculate(random.choice(new_content))

In [28]:
kk.get_result()

word:月　　　, center:1 , distance:0.9502
word:新华社　, center:1 , distance:0.9309
word:日　　　, center:1 , distance:0.9289
word:年　　　, center:1 , distance:0.8684
word:球员　　, center:0 , distance:0.7447
word:足球　　, center:0 , distance:0.6146
word:队　　　, center:0 , distance:0.5791
word:说　　　, center:2 , distance:0.5672
word:上　　　, center:2 , distance:0.5194
word:记者　　, center:2 , distance:0.5146


In [29]:
stopword_set += ['新华社', '日', '月', '2017', '记者', '摄', '照片', '年','外代']

In [30]:
new_content2 = [cut(c) for c in sample_content]

In [31]:
vectorizer2 = TfidfVectorizer(token_pattern='(?u)\\b\\w+\\b') # 默认pattern是只匹配长度至少为2的词
X2 = vectorizer2.fit_transform(new_content2)

In [32]:
X2.shape

(100, 5382)

In [33]:
def get_wv2(word):
    return X2[:, vectorizer2.vocabulary_[word]].toarray()

In [34]:
wordvec_dict2 = {}
for word in vectorizer2.vocabulary_.keys():
    wordvec_dict2[word] = get_wv2(word)

In [35]:
def test_kmeans(content):
    kk = keyword_kmeans(X2.T, wordvec_dict2, n_clusters=6)
    kk.calculate(content)
    kk.get_result()

In [36]:
test_kmeans(random.choice(new_content))

word:中　　　, center:3 , distance:0.7228
word:4　　　, center:3 , distance:0.6653
word:上　　　, center:0 , distance:0.5552
word:演员　　, center:4 , distance:0.4403
word:8　　　, center:3 , distance:0.3795
word:活动　　, center:2 , distance:0.3016
word:标志　　, center:0 , distance:0.2980
word:举行　　, center:2 , distance:0.2909
word:日晚　　, center:2 , distance:0.2749
word:副　　　, center:2 , distance:0.2584


对比一下textrank和kmeans

In [37]:
c = random.choice(new_content)
print('TextRank:')
test_textrank(c)
print()
print('Kmeans:')
test_kmeans(c)

TextRank:
word:外代　　　, weight:2.1085
word:老鹰队　　, weight:2.0896
word:2017　, weight:2.0012
word:4　　　　, weight:1.3511
word:斯卡拉　　, weight:1.3458
word:骑士队　　, weight:1.3160
word:老鹰　　　, weight:1.1936
word:照片　　　, weight:1.1893
word:球员　　　, weight:1.1866
word:年　　　　, weight:1.1510

Kmeans:
word:当日　　, center:4 , distance:0.8536
word:中　　　, center:4 , distance:0.8178
word:赛季　　, center:4 , distance:0.7914
word:球员　　, center:4 , distance:0.7910
word:战胜　　, center:4 , distance:0.7690
word:4　　　, center:4 , distance:0.7056
word:2016, center:4 , distance:0.7046
word:二线　　, center:4 , distance:0.5432
word:客场　　, center:4 , distance:0.5256
word:路透　　, center:4 , distance:0.4953


简评：

     可以看到，在小样本中，TextRank的效果比kmeans好很多。kmeans的主要问题在于cluster的数量需要人为设定，而且需要手动去掉特殊的停用词。

     kmeans的改进方向：修改distance的计算方法，引入大样本，对不同的cluster进行测试...这里主要就实现一下kmeans提取keywords算法，具体优化就不在这里进行了。

### 3.3  提取新闻人物里的对话。(使用以上提取小数据即可）

提示：    
1.寻找预料里具有表示说的意思。    
2.使用语法分析提取句子结构。    
3.检测谓语是否有表示说的意思。